#!/bin/bash
# /etc/init.d/thermometer

### BEGIN INIT INFO
# Provides:          servoblaster
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to measure enviromental values
### END INIT INFO

PIDFILE=/tmp/thermometer.pid

case "$1" in 
    start)
        echo "Starting thermometer"
        /home/pi/thermometer/server.py
        ;;
    stop)
        echo "Stopping thermometer"
        PID=`cat $PIDFILE`
        kill $PID
        ;;
    *)
        echo "Usage: /etc/init.d/thermometer start|stop"
        exit 1
        ;;
esac

exit 0
